general:
    default_charset: "UTF-8"
dev_garden:
    user: "yourdevguser@t-online.de"
    pass: "yourdevgpass"
imap:
    server_host: 'mail.yourmailserver.de'
    user: 'yourimapuser@yourdomain.de'
    pass: 'yourimappass'
    poll_interval: 10
sms:
    sender_name: "Email2Sms"
filter_chain:
    subject_filter:
        password: "Aihie4ca6a"
log:
    # dir_mode = normal => dir will be interpreted as dir
    # dir_mode = current => dir will be ignored. Logs will go to the folder from where
    #   the app has been started.
    dir_mode: "normal"
    dir: "default"