general:
    default_charset: "UTF-8"
dev_garden:
    user: "yourdevguser@t-online.de"
    pass: "yourdevgpass"
imap:
    server_host: 'mail.yourmailserver.de'
    user: 'yourimapuser@yourdomain.de'
    pass: 'yourimappass'
    poll_interval: 10
sms:
    sender_name: "Email2Sms"
filter_chain:
    subject_filter:
        password: "Aihie4ca6a"